In [3]:
print('hey there jupyter note book')

hey there jupyter note book


In [2]:
print('hello world')

hello world


In [ ]:
name = "rodney"

In [13]:
import numpy as np
X = np.zeros((3,4))
# print(X)
Y = np.full((3,3), 2)
# print(Y)
W = np.eye(5)
# print(W)
Z = np.linspace(0,10,10)
print(Z)

[ 0.          1.11111111  2.22222222  3.33333333  4.44444444  5.55555556
  6.66666667  7.77777778  8.88888889 10.        ]


In [15]:
X = np.arange(20)
print()
print("Original: ", X)
print()
X = np.reshape(X, (4,5))
print(X)


Original:  [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [32]:
A = np.random.randint(0,10,(3,3))
print(A)

[[1 1 5]
 [3 4 4]
 [9 3 0]]


In [29]:
B = A[0, :]
print(B)

[2 6 7]
